export const tShirts = [
  {
    id: 0,
    name: "Awesome black crop",
    src: "/assets/black-g-1.jpg",
    alt: "aw-black-crop",
    price: 50,
    availableColors: ["black"],
  },
  {
    id: 1,
    name: "Broken heart",
    src: "/assets/white-1.jpg",
    alt: "broken-heart-white",
    price: 40,
    availableColors: ["white", "yellow"],
  },
  {
    id: 2,
    name: "Black Plain",
    src: "/assets/black-1.jpg",
    alt: "black-plain",
    price: 50,
    availableColors: ["black"],
  },
  {
    id: 3,
    name: "Mordern crop",
    src: "/assets/white-g-1.jpg",
    alt: "mordern-crop",
    price: 60,
    availableColors: ["white", "yellow"],
  },
  {
    id: 4,
    name: "Tattoo fun",
    src: "/assets/blue-1.jpg",
    alt: "tattoo-fun",
    price: 40,
    availableColors: ["green", "blue"],
  },
  {
    id: 5,
    name: "Cool day",
    src: "/assets/grey-1.jpg",
    alt: "cool-day",
    price: 50,
    availableColors: ["grey", "brown"],
  },
  {
    id: 6,
    name: "Wonder lady",
    src: "/assets/orange-g-1.jpg",
    alt: "wonder-lady",
    price: 60,
    availableColors: ["orange", "yellow"],
  },
  {
    id: 7,
    name: "Dragon ball",
    src: "/assets/black-2.jpg",
    alt: "dragon-ball",
    price: 60,
    availableColors: ["black"],
  },
  {
    id: 8,
    name: "Awesome swag",
    src: "/assets/rose-1.jpg",
    alt: "awesome-swag",
    price: 50,
    availableColors: ["rose", "pink"],
  },
  {
    id: 9,
    name: "Denominator",
    src: "/assets/red-1.jpg",
    alt: "denominator",
    price: 60,
    availableColors: ["red"],
  },
  {
    id: 10,
    name: "Inspiring instance",
    src: "/assets/t-1.jpg",
    alt: "inspiring-instance",
    price: 50,
    availableColors: ["blue", "grey"],
  },
  {
    id: 11,
    name: "Happy flowers",
    src: "/assets/t-2.jpg",
    alt: "happy-flowers",
    price: 40,
    availableColors: ["white", "black"],
  },
  {
    id: 12,
    name: "Flowers special",
    src: "/assets/t-g-3.jpg",
    alt: "flowers-special",
    price: 40,
    availableColors: ["white", "black"],
  },
  {
    id: 13,
    name: "Paradise",
    src: "/assets/t-15.jpg",
    alt: "paradise",
    price: 50,
    availableColors: ["green", "white"],
  },
  {
    id: 15,
    name: "Express",
    src: "/assets/t-16.jpg",
    alt: "express",
    price: 60,
    availableColors: ["black", "white"],
  },
  {
    id: 15,
    name: "Formality",
    src: "/assets/t-18.jpg",
    alt: "formality",
    price: 50,
    availableColors: ["white", "grey"],
  },
  {
    id: 16,
    name: "Methodical Coffee",
    src: "/assets/t-19.jpg",
    alt: "methodical-coffee",
    price: 60,
    availableColors: ["grey"],
  },
  {
    id: 17,
    name: "Casual runner",
    src: "/assets/t-20.jpg",
    alt: "casual-runner",
    price: 40,
    availableColors: ["green"],
  },
  {
    id: 18,
    name: "Freestyle boy",
    src: "/assets/t-22.jpg",
    alt: "/assets/t-22.jpg",
    price: 18,
    availableColors: [],
  },
  {
    id: 19,
    name: "/assets/t-23.jpg",
    src: "/assets/t-23.jpg",
    alt: "/assets/t-23.jpg",
    price: 19,
    availableColors: [],
  },
  {
    id: 20,
    name: "/assets/t-5.jpg",
    src: "/assets/t-5.jpg",
    alt: "/assets/t-5.jpg",
    price: 20,
    availableColors: [],
  },
  {
    id: 21,
    name: "/assets/t-7.jpg",
    src: "/assets/t-7.jpg",
    alt: "/assets/t-7.jpg",
    price: 21,
    availableColors: [],
  },
  {
    id: 22,
    name: "/assets/t-8.jpg",
    src: "/assets/t-8.jpg",
    alt: "/assets/t-8.jpg",
    price: 22,
    availableColors: [],
  },
  {
    id: 23,
    name: "/assets/t-9.jpg",
    src: "/assets/t-9.jpg",
    alt: "/assets/t-9.jpg",
    price: 23,
    availableColors: [],
  },
  {
    id: 24,
    name: "/assets/t-g-10.jpg",
    src: "/assets/t-g-10.jpg",
    alt: "/assets/t-g-10.jpg",
    price: 24,
    availableColors: [],
  },
  {
    id: 25,
    name: "/assets/t-g-11.jpg",
    src: "/assets/t-g-11.jpg",
    alt: "/assets/t-g-11.jpg",
    price: 25,
    availableColors: [],
  },
  {
    id: 26,
    name: "/assets/t-g-12.jpg",
    src: "/assets/t-g-12.jpg",
    alt: "/assets/t-g-12.jpg",
    price: 26,
    availableColors: [],
  },
  {
    id: 27,
    name: "/assets/t-g-13.jpg",
    src: "/assets/t-g-13.jpg",
    alt: "/assets/t-g-13.jpg",
    price: 27,
    availableColors: [],
  },
  {
    id: 28,
    name: "/assets/t-g-17.jpg",
    src: "/assets/t-g-17.jpg",
    alt: "/assets/t-g-17.jpg",
    price: 28,
    availableColors: [],
  },
  {
    id: 29,
    name: "/assets/t-g-21.jpg",
    src: "/assets/t-g-21.jpg",
    alt: "/assets/t-g-21.jpg",
    price: 29,
    availableColors: [],
  },
  {
    id: 30,
    name: "/assets/t-g-4.jpg",
    src: "/assets/t-g-4.jpg",
    alt: "/assets/t-g-4.jpg",
    price: 30,
    availableColors: [],
  },
  {
    id: 31,
    name: "/assets/t-g-6.jpg",
    src: "/assets/t-g-6.jpg",
    alt: "/assets/t-g-6.jpg",
    price: 31,
    availableColors: [],
  },
];
